### ISSUE TITLE
Incorrect Kubeconfig provided when multiple replicas used

### ISSUE THREAD

**Issue by soggiest** [heptiolabs/gangway#108]
## What we're seeing
If there are multiple replicas of Gangway running there is a chance that a use will be provided another users' kubeconfig. 

## What we expected to see
A user is provided the correct kubeconfig every time.

## Notes 
This is caused by the Gangway created kubeconfigs being written to disk with the same name every time. Ovbiously this is a major security risk

## Proposed solutions
* Have new instances of Gangway check to see if another version is running and initiate a leader election, creating an active/passive configuration for Gangway
* Generate kubeconfigs for a user using a unique ID that can be referenced when a user downloads their kubeconfig.

**Comment by alexbrand** [comment]
Closing as this should be fixed by the merge of #89
