### ISSUE TITLE
A user in a sufficiently large number of groups will get a gangway_id_token too large for Chrome to set

### ISSUE THREAD

**Issue by nickperry** [heptiolabs/gangway#130]
Chrome has an upper bound on each cookie of 4096 bytes. I understand that some other browsers are limited to 4093 bytes.

A significant proportion of users in our organisation are members of enough LDAP groups to inflate the size of the gangway_id_token cookie in the response headers from /callback to be above this limit.

The result is that the cookie does not get set by their browser and is absent in their subsequent call to /commandline. They cannot therefore use Gangway to log in.

**Comment by nickperry** [comment]
It seems like the easiest cross-browser fix might be just to span the id_token data over multiple cookies with sequentially numbered suffixes. An additional cookie could be introduced to define the number of additional cookies that have been used and that need processing from a request.

**Comment by alexbrand** [comment]
Hey @nickperry! We have an open PR that addresses this: https://github.com/heptiolabs/gangway/pull/117

We haven't had a chance to look at it. It would be great if you could provide a testing data point, although the PR is most likely out of date with `master`.

**Comment by nickperry** [comment]
Thanks @alexbrand. I managed to overlook that PR. I will try it tomorrow and feed back. Many thanks.

**Comment by Croissong** [comment]
Rebased it onto master :)

**Comment by alexbrand** [comment]
Awesome @Croissong! Would be great to get this in. Thanks!

**Comment by nickperry** [comment]
@Croissong @alexbrand PR #117 works like a charm:

![image](https://user-images.githubusercontent.com/159528/57739062-03b19b80-76aa-11e9-847a-ce986b88cdbb.png)

Many thanks.

**Comment by nocquidant** [comment]
I can confirm it works great for me too. Thanks @Croissong

**Comment by nickperry** [comment]
Further to my artificially modified account testing last night, today we've had multiple real users who could not login previously, report that they can now log in fine with @Croissong's patch.

**Comment by HerrmannHinz** [comment]
is this ticket closed? i see something is merged.

**Comment by jenting** [comment]
yes, and includeed in release `v3.2.0`

**Comment by jenting** [comment]
> is this ticket closed? i see something is merged.

yes, and included in release `v3.2.0`

**Comment by alexbrand** [comment]
Yep! Closing as this was fixed by #117

**Comment by HerrmannHinz** [comment]
Nice thanks

-- 
--------------------------------
Tobias Herrmann Hinz
mobil: 0162 212 9613
--------------------------------
