### ISSUE TITLE
Update dns command

### ISSUE THREAD

**Issue by rbankston** [heptiolabs/gangway#141]
kubectl get svc -n heptio-contour contour -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'

should be

kubectl get svc -n projectcontour envoy -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'

in https://github.com/heptiolabs/gangway/blob/master/docs/README.md

**Comment by jenting** [comment]
In my test, the namespace and service name does not change.

**Comment by rbankston** [comment]
Hi @jenting I chose the wrong manifest some of them use projectcontour is used and envoy gets the ELB. Closing for now. May change when 1.0 is officially released.
