### ISSUE TITLE
[session/session.go] Should session information be stored or ignored?

### ISSUE THREAD

**Issue by soggiest** [heptiolabs/gangway#16]
Encountered the following error in my browser after killing a Gangway pod and letting it restart:
`securecookie: the value is not valid`

Problem went away when attempting to reach Gangway via a private window

It looks like the gorilla/session code is storing data in a way that is sub-optimal per this older bug:
https://github.com/gorilla/sessions/issues/16

I'd like to investigate this issue.

**Comment by johnbalvin** [comment]
You may be have `var store = sessions.NewCookieStore(securecookie.GenerateRandomKey(10))`, or any random key,  this cause that each time you restart the server, a new key will be created, the key is to encode and decode the cookies, so if a new key is been used and previously you have saved a cookie into web browser, then it will cause that error, you should use an static key that can be reused, see https://github.com/gorilla/sessions/issues/16
