### ISSUE TITLE
Multiple replicas

### ISSUE THREAD

**Issue by yhaenggi** [heptiolabs/gangway#161]
Hey

In the deployment yamls, you specify 1 replica. We would like to deploy it with multiple replicas. Are there common problems with this, or why did you specifically set it to 1 instead of leaving it out?

BR

**Comment by jenting** [comment]
You could set to multiple replicas by `kubectl scale --replicas=<N> deploy gangway`.

If you want to do multiple pod HA, it's better to set node affinity rule to let each pod runs on the different hosts.

**Comment by yhaenggi** [comment]
Im aware how to scale/set replicas. The questions is if gangway is fully stateless and has no issues with multiple replicas.

**Comment by jenting** [comment]
AFAIK, it's a stateless application.
Moreover, we run the default 3 replicas in our Kubernetes cluster, everything run well :wink:

**Comment by yhaenggi** [comment]
Thanks for the information.
