### ISSUE TITLE
Upgrading to v3.3.0?

### ISSUE THREAD

**Issue by sherifkayad** [heptiolabs/gangway#186]
Currently there's a big gap between the latest master and the latest release 3.2.0 .. Are there any plans to issue a new release soon?

**Comment by sherifkayad** [comment]
CC: @stevesloka

**Comment by stevesloka** [comment]
Hey folks! Sorry about this, let me pop in and see if I can get things squared up. =)

**Comment by sherifkayad** [comment]
@stevesloka any updates on that?

**Comment by stevesloka** [comment]
@sherifkayad sorry for the delay, I'm on PTO this week, will be able to get to it next week. I started to update some of the deps to make a proper release which is also why things got delayed a bit last week.

**Comment by sherifkayad** [comment]
@stevesloka amazing! Thanks for the update

**Comment by stevesloka** [comment]
@sherifkayad chatting with folks on where to put images for this since the Heptio bits are long deprecated after our move to VMware. I can make a release, but you'd need to build your own image at the moment.

**Comment by sherifkayad** [comment]
@stevesloka no issues .. I can do that .. another easy idea would be pushing to the GitHub Container Image Repo .. how does that sound?

**Comment by stevesloka** [comment]
Hey @sherifkayad I just published the latest release v3.3.0.

The other bit is that we're going to hold dev on the project since it's been idle for some time. I'm updating the project now, but please let me know if you have any questions! =)
