### ISSUE TITLE
Big cookies do not work

### ISSUE THREAD

**Issue by hoegaarden** [heptiolabs/gangway#26]
We came across this issue when having gangway use [UAA](https://github.com/cloudfoundry/uaa) which gave us quite large tokens.

When the securecookie is bigger then 4k (which seems to be the [maximum cookie size](http://browsercookielimits.squawky.net/) on all major browsers) then the cookie is not stored. When `/callback` then redirects to `/commandline` the `loginRequired` middleware "fails" and redirects back to `/`, we never hit `/commandline`.
If we switch from the session store from `CookieStore` to `FilesystemStore` the whole flow seems to work and we end up hitting the `commandlineHandler`.

Things we could do to help here:
- when the cookie is ~4k have gangway log a warning
- make the session store configurable (let users switch between `CookieSession` and `FilesystemSession` and potentially others)

**Comment by kvaps** [comment]
Same problem for me, message:

```
securecookie: the value is too long
```

**Comment by kvaps** [comment]
Switched to Kuberos, working fine

**Comment by stevesloka** [comment]
Let me see if I can make this configurable @hoegaarden.

**Comment by paulczar** [comment]
I somewhat clumsily solved this in #80 by creating multiple cookies and putting the tokens in their own.
